const GENERATE_AND_SEND_EVENTS_AND_USERS = 0
const GENERATE_AND_WRITE_USERS_TO_REDIS = 1
const GENERATE_AND_SEND_EVENTS_WITH_USERS_READ_FROM_REDIS = 2
const SEND_USERS_ON_REDIS = 3

export default {
  GENERATE_AND_SEND_EVENTS_AND_USERS,
  GENERATE_AND_WRITE_USERS_TO_REDIS,
  GENERATE_AND_SEND_EVENTS_WITH_USERS_READ_FROM_REDIS,
  SEND_USERS_ON_REDIS
}
